/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const { scene, animations } = useGLTF('/LittlestTokyo.glb')

  const { actions } = useAnimations(animations, scene)

  useEffect(() => {
    actions["Take 001"].play()
  });
  return (
    <primitive object={scene} {...props}/>
  )
}

useGLTF.preload('/LittlestTokyo.glb')
