/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { scene } = useGLTF('/girl/scene.gltf')
  return (
    <primitive object={scene} {...props} />
  )
}
